eoscostarica/es.eoscostarica.io

- docusaurus.config.js
- package.json
- yarn.lock
- update docusarus version 
- update docusaurus config
- add google analytics
> fix(config): add google analytics and update packages

- src/css/custom.css
- src/pages/styles.module.css
- src/theme/styles.module.css
- Add same font to text area
- Adjust menu width for mobile version
- Fix UI issues 
1. run yarn start
1. go to localhost:3000
1. test the web app
> Fix UI issues mobile usability

- src/pages/prensa.js
> update(content) change news on press page

- src/pages/contactenos.js
- src/pages/do-you-need-blockchain.js
- src/pages/equipo.js
- src/pages/index.js
- src/pages/la-empresa.js
- src/pages/productor-de-bloques.js
- src/pages/proyectos.js
- src/pages/servicios.js
> update(content): change metadata pages

- src/css/custom.css
closes #324
- Fix blog header
- go to http://localhost:3000/blog
> fix header blog

- src/theme/Footer.js
> Fix broken footer links

- src/css/custom.css
- src/pages/Animations/Games.js
- src/pages/Animations/Payments.js
- src/pages/block-producer.js
- src/pages/components/AdditionalResources/index.js
- src/pages/industrias.js
- src/pages/la-empresa.js
- src/pages/prensa.js
- src/pages/servicios.js
Resolves #56
Resolves #57
Resolves #58
> Fix front-end details

- src/pages/contactenos.js
- src/pages/index.js
- src/pages/la-empresa.js
- src/pages/servicios.js
- src/theme/NotFound.js
> Corrections in spanish version

- package.json
- src/css/custom.css
#68
1. Change form the load font
> Mobile menu has a different font

- src/css/custom.css
- src/pages/la-empresa.js
> Add jobs section to team page

- src/css/custom.css
- src/theme/BlogPostItem/index.js
- src/theme/BlogPostPage/index.js
- src/theme/Navbar.js
resolves #64 
- improve design on languague selector
- fix blog design details
> fix: design details

- src/pages/proyectos.js
#61
1. Add gGoods to projects page
1. Swap order between SMARTGATE and Lifebank
> Add gGoods to projects Spanish website

- package.json
- src/plugins/webpackconfig/index.js
> Fix details

- package.json
- src/plugins/webpackconfig/index.js
#86 
- Change docusaurus import package version
> Fix deploy bugs

- src/pages/components/LacchainForm/index.js
1. Add recaptcha key on lacchain form
> Add recaptcha key

- src/theme/Navbar.js
#114 
1. Fix change language on lacchian landing page
> Fix bug: lacchain eosio landing page change language is bad

- src/pages/equipo.js
Actualicé mi enlace a twitter.
No hay issue.
No hay test.
> Enlace a Twitter

- src/theme/BlogPostPage/index.js
> fix(blogPostPage): comment line

- src/css/custom.css
- src/theme/BlogPostPage/index.js
- src/theme/Navbar.js
> Fix blog pages

- src/pages/block-producer.js
- src/pages/index.js
- src/pages/la-empresa.js
- src/pages/proyectos.js
- src/pages/servicios.js
> Apply chances in content

- src/css/custom.css
- Resolves #135 
1. Run `yarn build`
2. Run `yarn start`
3. Go to `localhost:3000`
4. Go to Developers Guidelines >
> Overwrite css image property 

- README.md
- src/pages/block-producer.js
- src/pages/components/AdditionalResources/index.js
- src/pages/index.js
- src/pages/la-empresa.js
- src/pages/proyectos.js
- src/pages/servicios.js
- Resolves #142 
1. Run `yarn build`
2. Run `yarn start`
3. Go to `localhost:3000`
4. Go to Website Pages
> feat(src): add new content to pages

- src/pages/block-producer.js
- src/pages/index.js
- src/pages/la-empresa.js
- src/pages/proyectos.js
> Changed eosio dashboard content to antelope tools
